fluentform/fluentform

- readme.txt
> Minor readme update

- app/Helpers/Helper.php
- app/Hooks/Backend.php
- app/Services/FormBuilder/Components/SelectCountry.php
- app/Services/FormBuilder/DefaultElements.php
- app/Services/FormBuilder/ElementSettingsPlacement.php
- fluentform.php
- resources/assets/public/form-submission.js
Please check
1. Elementor Modal Recap Issue
2. Bulk Mark as Read/Unread
3. Smart Search for Country List
> First Commit 

- app/Services/FormBuilder/EditorShortCode.php
- app/Services/FormBuilder/EditorShortcodeParser.php
Returns Random string with uniqid() and user provided prefix
> Shortcode for generating a random string

- app/Modules/Component/Component.php
- app/Modules/Form/Form.php
- resources/assets/admin/components/settings/FormSettings.vue
- resources/assets/admin/components/settings/FormSettings/Restrictions.vue
Added weekday day array option and checked with scheduled date scheduleForm method
> Added weekday option with date restriction

- resources/assets/admin/views/FormEditor.vue
Loading Text typo fixed to - Loading Awesomeness
> Typo Fixed in FormEditor

- app/Modules/Component/Component.php
- resources/assets/admin/components/settings/FormSettings.vue
- resources/assets/admin/components/settings/FormSettings/Restrictions.vue
Skip checking if no value was set initially and show all date is selected initially
> Fix weekday restriction

- resources/assets/public/Pro/slider.js
Repeater fields value is updated but does not show in input value , added val() setter to update the value
> Fix repeater field issue for form step data save

- app/Services/FormBuilder/Components/Name.php
- resources/assets/admin/components/editor-field-settings/templates/fieldOptionSettings.vue
- resources/assets/public/scss/_public_helpers.scss
Added name field title prefix with dropdown option
> Name field prefix

- resources/assets/admin/components/modals/predefinedFormsModal.vue
Updated label for new post form in predefined forms modal
> Label Update for Predefined Forms Modal

- resources/assets/admin/components/settings/GeneralIntegration/_ChainedFields.vue
Updated the chained_fields component  to fetch data from the passed url
> Fix MailChimp Interest Group fetching

- app/Hooks/Ajax.php
- app/Modules/Entries/Entries.php
- app/Modules/Form/Settings/EntryColumnViewSettings.php
- resources/assets/admin/css/settings_global.scss
- resources/assets/admin/form_entries_app.js
- resources/assets/admin/views/ColumnDragAndDrop.vue
- resources/assets/admin/views/Entries.vue
Added two form meta for visible columns and columns display order to show/hide columns in entries page, change column display order
> Added entries column selective display option and column display order

- app/Hooks/Ajax.php
> Fix Entry Column View Settings

- app/Services/Integrations/MailChimp/MailChimpIntegration.php
- app/Services/Integrations/MailChimp/MailChimpSubscriber.php
MailChimp unsubscribed contact will be updated as subscribed or pending
> Added ReSubscribe option for MailChimp

- resources/assets/admin/components/settings/SettingsApp.vue
- resources/assets/admin/views/Entries.vue
It was missing from entries and settings page
> Fix show shortcode copy success message

- resources/assets/admin/components/input-popover.vue
> Fix input-popover.vue

- app/Modules/Logger/DataLogger.php
- resources/assets/admin/transfer/ApiLogs.vue
- resources/assets/admin/transfer/transfer.js
- resources/assets/admin/views/SubmissionLogs.vue
- resources/views/admin/transfer/index.php
> Added api & activity logs page separately

- app/Modules/Component/Component.php
- resources/assets/public/form-submission.js
maxItemTextLang was a unknown config item ,changed to maxItemText
> Fix - ChoiceJS Vars

- resources/assets/admin/transfer/ActivityLogs.vue
- resources/assets/admin/transfer/ApiLogs.vue
Screenshot : https://prnt.sc/1qi2htc
> API & Logs Page filter left alignment

- app/Modules/Form/FormHandler.php
added current WP time for checking
> Update malicious submission prevention 

- app/Modules/Component/Component.php
Example : [fluentform_info id="1" info="submission_count"  payment_status="paid"]
> added payment status for submission_count helper shortcode

- resources/assets/admin/components/settings/FormSettings.vue
- resources/assets/admin/components/settings/Includes/AdvancedValidation.vue
Screenshot: https://prnt.sc/21ntk9y
> Typos and grammatical error in form settings page

- app/Modules/Widgets/FluentFormWidget.php
> added search option to the select field

- resources/assets/public/Pro/file-uploader.js
https://lounge.authlab.io/projects#/boards/16/tasks/11541-Wrong-error-on-Uploading-file-
> Fix: file upload error message clear

- app/Modules/Payments/AjaxEndpoints.php
https://lounge.authlab.io/projects#/boards/16/tasks/11140-When-Payment-status-is-changed
> Fix: payment status changed not trigger notifications

- app/Services/FluentConversational/Classes/Converter/Converter.php
https://lounge.authlab.io/projects#/boards/16/tasks/10725-Address-field-prints-Shortcode
> Fix: conv form address default value shortcode

- app/Api/Submission.php
- app/Modules/Payments/TransactionShortcodes.php
https://lounge.authlab.io/projects#/boards/16/tasks/11899-fluentform_payments-
> Fix: fluentform_payments shortcode subscript type/status

- app/Services/FluentConversational/Classes/Converter/Converter.php
- app/Services/FluentConversational/Classes/Form.php
- app/Services/Form/FormValidationService.php
- app/Services/FormBuilder/ShortCodeParser.php
1. Fix: save chat waiting message on submission meta -
https://lounge.authlab.io/projects#/boards/16/tasks/11859-Forms-AI-Confirmation-Waiting-
2. Fix: ipinfo error on keyword restriction check - https://lounge.authlab.io/projects#/boards/16/tasks/11190-Ipinfo-error-with-ke
3. Fix: conv form save and resume custom html - https://lounge.authlab.io/projects#/boards/16/tasks/10827-Per-Step-Data-save-dosen't-wor
> Forms AI Confirmation Waiting Message Control

- resources/assets/public/payment_handler.js
https://lounge.authlab.io/projects#/boards/16/tasks/10933-Multiple-Coupon-remove-coupon-
> Fix: coupon remove summery not update

- resources/assets/admin/views/Entry.vue
https://lounge.authlab.io/projects#/boards/16/tasks/10354-Multi-select-field-issue-when-
> Fix: multi select with comma used options

- assets/js/fluent_gutenblock.js
- resources/assets/public/Pro/slider.js
https://lounge.authlab.io/projects#/boards/16/tasks/11554-Step-form-animation-enhancemen
> Enhance step Animation

- app/Helpers/Helper.php
- app/Modules/Component/Component.php
- app/Modules/Payments/PaymentHandler.php
- resources/assets/public/payment_handler.js
https://lounge.authlab.io/projects#/boards/16/tasks/11988-Fix-separate-free-pr
> Fix: separate free & pro payment handler script

- app/Services/FluentConversational/Classes/Converter/Converter.php
https://lounge.authlab.io/projects#/boards/16/tasks/12096-Conversational-form-
> Fix: conversational form invisible turnstile

- app/Modules/Payments/Classes/PaymentEntries.php
- assets/js/fluent_gutenblock.js
- resources/assets/admin/PaymentEntries/Components/payments.vue
https://lounge.authlab.io/projects#/boards/16/tasks/12097-New-filter-on-paymen
> New: Payment types filter

- resources/assets/public/payment_handler.js
https://lounge.authlab.io/projects#/boards/16/tasks/9064-Coupon-code-discount
> Fix: coupon code discount min purchased amount

- resources/assets/admin/components/editor-field-settings/templates/advanced-options.vue
https://lounge.authlab.io/projects#/boards/16/tasks/12251-Radio-field-customiz
> Fix: radio field editor selecting default value

- app/Services/FormBuilder/FormBuilder.php
- resources/assets/public/Pro/form-conditionals.js
- resources/assets/public/form-submission.js
https://lounge.authlab.io/projects#/boards/16/tasks/12183-Conditional-Logic-do
> Fix: conditional logic for Repeat Container

- app/Services/FluentConversational/Classes/Converter/Converter.php
https://lounge.authlab.io/projects#/boards/16/tasks/9210-Quantity-Mapping-in-
> Fix: conv form range slider qty mapping

- resources/assets/public/Pro/slider.js
https://lounge.authlab.io/projects#/boards/16/tasks/11033-Star-Rating-Field-an
> Fix Rating not selected save & resuming

- app/Helpers/Helper.php
- app/Modules/Form/FormDataParser.php
- app/Services/FormBuilder/Components/TabularGrid.php
- app/Services/FormBuilder/FormBuilder.php
https://lounge.authlab.io/projects#/boards/16/tasks/11382-Checkable-Grid-shows
> Fix: checkable grid multiple space

- app/Helpers/Helper.php
- app/Services/Form/FormValidationService.php
- resources/assets/admin/components/settings/Includes/AddConfirmation.vue
Conversational form with Terms & Conditions field shows "The Given Data Was Invalid" error when not accept option selected
https://lounge.authlab.io/projects#/boards/16/tasks/10435-Terms-Conditions-Fie
> Fix: conv form gdpr not accept option error

- .gitignore
- app/Helpers/Helper.php
- app/Helpers/Str.php
- app/Services/FormBuilder/Components/Address.php
- app/Services/FormBuilder/DefaultElements.php
- app/Services/FormBuilder/EditorShortCode.php
- app/Services/FormBuilder/ShortCodeParser.php
- app/Services/Integrations/MailChimp/MailChimpSubscriber.php
- app/Services/Migrator/Classes/CalderaMigrator.php
- app/Services/Migrator/Classes/GravityFormsMigrator.php
- app/Services/Migrator/Classes/WpFormsMigrator.php
- app/Services/Parser/Extractor.php
- assets/js/fluent_gutenblock.js
- resources/assets/admin/components/editor-field-settings/templates/addressFields.vue
- vendor/wpfluent/framework/src/WPFluent/Database/ConnectionResolver.php
- vendor/wpfluent/framework/src/WPFluent/Database/Orm/Relations/Relation.php
- vendor/wpfluent/framework/src/WPFluent/Database/Query/Builder.php
- vendor/wpfluent/framework/src/WPFluent/Pagination/LengthAwarePaginator.php
- vendor/wpfluent/framework/src/WPFluent/Pagination/Paginator.php
- vendor/wpfluent/framework/src/WPFluent/Pagination/PaginatorInterface.php
- vendor/wpfluent/framework/src/WPFluent/Support/Collection.php
- vendor/wpfluent/framework/src/WPFluent/Validator/ValidationRuleParser.php
- Added lat lang in shortcode list
- with backward compatibility
> Added Html5 location support in address field 

- app/Services/Form/FormValidationService.php
https://lounge.authlab.io/projects#/boards/16/tasks/12929-Keyword-restriction-
> Fix: keyword restriction comma after last

- resources/assets/common/_wp_editor.vue
https://lounge.authlab.io/projects#/boards/16/tasks/13208-Confirmation-message
> Fix: confirmation message URL sanitize

- resources/assets/public/form-submission.js
- resources/assets/public/scss/choices.scss
Adds dynamic height adjustment and enhanced touch event handling for Choices.js dropdowns on all devices in form-submission.js. Updates choices.scss with improved mobile styles, touch area expansion, and better scrolling behavior for dropdowns, ensuring a smoother and more accessible experience on touch devices.
https://lounge.authlab.io/projects#/boards/16/tasks/13303-Scroll-doest-work-pr
https://support.wpmanageninja.com/#/tickets/134497/view
> Improve: select with Choices.js all devices scrolling

- app/Modules/Registerer/TranslationString.php
- app/Modules/Widgets/FluentFormWidget.php
- app/Services/FluentConversational/Classes/Fonts.php
- resources/assets/admin/components/editor-field-settings/templates/advanced-options.vue
- resources/assets/admin/components/editor-field-settings/templates/pricing-options.vue
- resources/assets/admin/conversion_templates/conversational_design.js
- resources/assets/admin/editor_app.js
- resources/assets/admin/views/MoreMenu.vue
https://lounge.authlab.io/projects#/boards/16/tasks/13266-Namingspellingcopy-e
> Fix: Naming + spelling + messages

- app/Services/FluentConversational/Classes/Form.php
- resources/assets/admin/conversion_templates/Parts/DesignElements.vue
https://lounge.authlab.io/projects#/boards/16/tasks/10730-Scroll-to-top-featur
> Add: conv form scroll to top

- app/Modules/Registerer/Menu.php
- resources/assets/admin/components/settings/GeneralIntegration/IntegrationEditor.vue
- resources/assets/admin/settings/GeneralIntegrationSettings.vue
This reverts commit 149d747058fd0c9fd8d4451ea7ee23284e720279.
> Revert: google-sheet

- resources/assets/public/payment_handler.js
https://lounge.authlab.io/projects#/boards/16/tasks/13648-Payment-summary-fiel
https://support.wpmanageninja.com/#/tickets/137841/view
> Fix: js translation string method

- resources/assets/public/scss/choices.scss
https://lounge.authlab.io/projects#/boards/16/tasks/13793-Multiple-Choice-Fiel
https://support.wpmanageninja.com/#/tickets/135488/view
> Improve: multi select dropdown for elementor popup

- resources/assets/common/_wp_editor.vue
https://lounge.authlab.io/projects#/boards/16/tasks/13290-PDF-Download-link-in
> Fix: PDF download link in confirmation

- resources/assets/public/scss/public/components.scss
https://lounge.authlab.io/projects#/boards/16/tasks/13723-Steps-Forms-Bugs
> Fix: phone field search input style

- app/Services/Spout/Common/Singleton.php
https://lounge.authlab.io/projects#/boards/16/tasks/13786-PHP-8-Compatibility-
> Fix: PHP 8 Compatibility issue with Excel Export

- resources/assets/public/Pro/dom-repeat.js
- resources/assets/public/Pro/slider.js
https://lounge.authlab.io/projects#/boards/16/tasks/13376-Save-and-Continue-Fe
> Fix: repeater container save and resume

- app/Modules/Ai/AiFormBuilder.php
Need to update updated ai-workder.js on https://ai.fluentforms.com/
https://lounge.authlab.io/projects#/boards/16/tasks/13233-AI-CSS-support-in-fo
> Add: FF ai form builder custom css js support

- app/Hooks/filters.php
- app/Modules/Form/FormDataParser.php
https://lounge.authlab.io/projects#/boards/16/tasks/10597-Entires-table-shows-
> Fix: checkable fields labels for entires table

- resources/assets/public/payment_handler.js
https://lounge.authlab.io/projects#/boards/16/tasks/18342-Payment-Form-Submiss
> Fix: elementor popup payment submission
